name: Run All Tests
on:
  push:
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Run uiua tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable && rustup default stable
      - run: cargo install --git https://github.com/uiua-lang/uiua uiua
      - run: uiua test advent-of-code